version: '3.5'
services:
  nginx: 
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./front/public:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - flask
    networks:
      - backend

  flask:
    build:
      context: flask/
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./flask:/code
    environment:
      FLASK_ENV: development
    networks:
      - backend

networks:
  backend:
    name: backend
